language: scala

scala:
  - 2.11.12

sudo: false
script: $TRAVIS_BUILD_DIR/travis/script/build.sh

jdk:
  - oraclejdk8

cache:
  directories:
  - $HOME/.m2
  - $HOME/.ivy2
  - $HOME/.sbt

git:
  submodules: false

addons:
  apt:
    packages:
      - ffmpeg

before_install:
  - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
  - git submodule update --init

env:
  global:
  - secure: sOjqcUXlpX77hL+qWMcoPujyttu6xo0BodJhqHMIipnnm2T/sfeoDxdqjgky4pQLN2WUMjIt7UItmVOProgbxNLXLFXjHzNmtuUfRiY8MSbuuFEt99b7P9wW/WG1qJ4FyWzaaxV/XANx060U552TNdRYiIvmcwbeKB7B8NOlkHEFcurqHIvkeHFOzBlJKvCFQTvwV/xQ59bIHwlUSTEza0sdnGt1Ab+FiyusBPFdDcMCY9H2jASXPBKwif4McWdNtPiG3uEUhxtwgy2679cL0T0LPXiEi+dfW+rd95agvKkx7guAZ1JemOh0u7u6h1tReikg608eQYB68Y8135XVzemLrA+EwvFs7piEKn5wATz73s4m/RWKONzIzprtsNMvApAemvbNE2IfjwZXdmp8Y8vMmEPLl9fhI6R0SDSJ2FGT8uVZYmiPNwB2qVsI4xDSIqMmWejp0+J/qnGlkjDnPRGHRwdLlcmSXu/FV0qnSb/9lLLYQPc/stKaNzMJlSdegRo0Upa7yUMF5TYqgXGd6CDItL1seXDNCjBBN54+hTQBORSCDqhGEKQKtWI+ziOezJoHQ/MGbMaLqUZCcveZX5Qd3yY5IVBNQVr+pomPiCXSgIWuw+DeIOYJAwlR91VdulxwzGH+DVw1ZYN73IsHRSJ8yTLfm83ZC2Pro15jgf8=
  - secure: UrerAcEYOOshTNyjdXTJp7XeEbNUYIzUME7xR3ow2wZCp4mynVmrmuQ0wgSSIbdy4mmN3AmWWvkDnARpIcegEELy4pW/JFK8AZRman9qkjqqoMNYWIQgLj7M14Llgzf7zHRNddvNS7rcc/ZYXVwv605AG+iI+En8yURARaWX4rJtomNTHTCyJ4jxYMgEnDnJOpzv6B6nnlGw+GRaJqQ6j6I3RBJ/YWLHsonBkp8NfmkcEE4xei7YfIsmn+FV42eiF8wBHOWV6Nd4DkyIfkMX4Q0SzMsSxVDGb13F4isYzHPY1Ft+HYcJ99Q/z0GVMTNhaw2K0H4hvwEYVcL/iI/JacyK3Igclfg0uw6+AJ39qmCCkjFOrS2UPNNEI6wR0wddIF++BSC/gU9O6h8l2KP/0PMlwpAIi9F4y9vOwtaC74cGsPoq90dhJdLAh21n9Nh7CrL26y0XJ+iS3od11tdilO46pHOhPc6EhbDHIcfoLVEm9ng+ATyatBNPPrI5OoPrAjlzPLjL18UJuOXsitMoaD1YSxSXHBWt5+nXbhupSbsbJge9jTTW8t+DcgksjJrWk2Iu4fAwratHy08f1RLbljcOg5IZo1R5j/mNqS9rnVubF5rF7kKbOyx9zFKVYEy4wHXaQzTRJeylrvSN23b0tdoxKieIUOTefkVCxgT8BqQ=
  - secure: S8w+oEhBJUWFzV5P3HCfij7bGF9yuUUambgO6LnGfjUYXxBHiFbYyil9WriznK25tVs5m5trpawZD+yDK1L2LMR659fGcmAMdaPSUcsnr51UFcm4pipBXhI2GC19nVEjgSWfNzCVp70hPUP0G0A+ATH+C1XRZkgMb1yki2tddHQzsanQlg4zQKohg9kL9TQH0vC/6bOulw3yOIX3JMiJPwLs+JkOBglWftJRRoF+SPniWxyoKM4/bnS98x8sdO9bm5J04CpSn/jzrrUaeh8Wq0mHhvRhEgIluWLYju7srPrbRth0pPZ6vIwwmJ3MUJR1ewsrro+Uxb37H6PBHyWzqSX+RRlvV4E2/Rm5MC+eYDbdnCPPEXJZInhSXrt1KgEvhfrQ+XseNPy76GWo1tbVTfRw9Sb7DYJco6JRKewEUgdZqszmtM6kZVOxg/0WskJ4d5RuHr9x98cewD+gX6SkZ2tROfOht9BLTZLnnWUvJd9At625krD9lOLhjef65euI8UBsR/VBL0wE0IYbC2XUEEqUbMiM7HrzdgTk8w28gLPiEoJUPtO8wqGJlQYP+yxkWmF5xYJupspr0j3wU+1r6Y1owbykj5hS7kuZYLB5gOYLLTPU3lLskM9FUa+O5/Th72mXdiLJZPBOAXUXyK9rzk4BxolXh9IAL8pD4Jh6xy4=
  - secure: TQ4FgRVC1QzIUqshcGRlXxGkribHuGMAL1nroiSDeJiQHhUYvwA38dry0hJJ4R+r+3BAoJzA7ZfFHRlhKMjEhBCabQ5pizPqeoX7g1daZzlHvW3tlo3osr0h5g5LP6BuUA9QuaNZLUhfEzyNq0tIHSYmO75JoBJosOJcmMD6Q4fIWIpEh5GxdyEzBkTlpweLYDpmv/+PkCthljTB//y0hTNcHlZAnKW5Ds2jk7uGNQspU5YvJRcPoU8tkK6NOc3/bpxSM8292unWkrptoTNw9cxDPWzB4l01mATIHleT5N6NjIYFViqSkzultqV8YUgJX12+2YfZ/Z3jfLkg1Si7xjnyyTfzLSWrgYi0+Rwpa5bzDa3KmYtfnO5W3UBDvfPqJC+NfZr7vtzOfR/MofFh8bVmEczYqUfaIHK4NXU3EGnLLkXOo+PVBGrVoHzi9G6jtiAZdCLG3kBTOqyNz7V0nOIEedDcytW8qJsfsLOt+oBnZVqBgMZx8izrUFcAid30ZLmnZQLkd6B1hezHGMXBUQyJBsE5ljoIRKqUfHULWFNKMhxenGP/gf9cpNicCJB/Nus716pwG1cH3AaKl9r0/LkfUuKnh1O2HTmN2ddn8NDw5YbBzVdAP51iZDWEyqlZHBE8F/XRtN3DOtlVcywhpy7xCrL1IG4MX9zKJmxdQW4=
